#logging:
#  level:
#    .: error
#    org.springframework: ERROR
#    com.westat.ctsu: INFO
#    
#        
#---
#appConfig:  
#####################################################################################################
#
#  jiraProps:
#      url: jiraUrl
#      username: jiraUser
#      password: jiraPwd
#  
#  svnProps:
#      url: svnUrl
#      username: svnUser
#      password: svnPwd
#  
#  #Template Location (Source & Target)
#  uiSourcePath: C:\\yandagudita_s\\V3.0m2-angular-cli\\navigator\\src\\app\\pages\\
#  serviceTemplateName: ./template/CTSU-CENTER-SystemDesignContentTemplate.docx
#  uiTemplateName: ./template/CTSU-BIOSPEC-SystemDesignContentTemplateUI.docx
#  
#  #templateConfig:
#  generationType: BATCH #SINGLE/BATCH  
#  templateEnum: SERVICE
#  offlineReqJira: true
#  changeListEnum: SVN #PROJECT
#  rootPackage: #should be configured if changeListEnum: PROJECT
#  workItems:  CNTR-470  #CNTR-470 #NAVI-721, CNTR-457
#  #jiraQuery:   project = CENTER  AND fixVersion = 4.0
#  moduleName:  #CENTER-4.0 useful for SINGLE doc generation type
#  pathBreaker: portal #portal, nav-service